### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by 3TUSK**

### CODE REVIEW

**Comment by copygirl** [comment]
Thanks! I already received a translation for Chinese.
https://gist.github.com/copygirl/31a6692f7c91ca5cf41b1827e097c91c
Can you have a look over it and maybe work it into the PR?

**Comment by 3TUSK** [comment]
May I ask where did you get that? I probably know him/her.

**Comment by copygirl** [comment]
They introduced themself as FantasyWings.

**Comment by 3TUSK** [comment]
Wait, *they*? And that name recalled me to nothing.

I could just manually merge both of theirs and mine, but I'd prefer to get touch on them...

**Comment by copygirl** [comment]
I use [singular they](https://en.wikipedia.org/wiki/Singular_they) because I don't know if I should use he or she. I don't know if it's okay to give out their email address. I will ask.

**Comment by copygirl** [comment]
@3TUSK Here is their email address: zhijun@urlgeek.com

**Comment by copygirl** [comment]
Did you get to talk at all?

**Comment by 3TUSK** [comment]
@copygirl sorry but I was busy on many irl things recently

**Comment by copygirl** [comment]
Commit 3f081f27ceaaf823c50a481544db3dede3eef12e removed the "rows" and added a "size" setting instead. (Also the category translation key has been removed.) Please take a look at [the new language file](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/resources/assets/wearablebackpacks/lang/en_US.lang) and update yours accordingly. Thank you!

**Comment by copygirl** [comment]
I'm getting ready for the next release. Could you perhaps look at updating this PR again?

**Comment by 3TUSK** [comment]
Apologize for long over due. I am graduating high school student irl so I have less time in recent months. 
I looked at the translation you provided again, but this time I highly doubt on that. I mean, that translation *is* okay, but not native enough in my eyes. 
Either way, I pushed another commit, aiming to merge two translation together.

Guess I need to call someone else to proof read this? @TartaricAcid

**Comment by TartaricAcid** [comment]
To be honest, I approve 3TUSK's translation, another translation seems that lack punctuation, resulting in a more difficult to understand.

**Comment by copygirl** [comment]
Thanks for looking into it. I updated the PR with the new translation keys. If you get a chance to do these as well, that would be neat. Otherwise I'll simply merge the PR before the next release.

**Comment by TartaricAcid** [comment]
thank you

**Comment by 3TUSK** [comment]
Update pushed.

Regarding the two different version: I will see if I can get on touch with them by any chance. Right now I am in my school finals week, so this may cost time.

**Pull request merged**
