### PR TITLE
Added Danish localization

### PR DESCRIPTION
**Pull request by Zerotiger**
Please credit using my CurseForge username "Ruukasu" or "Ruukas": https://minecraft.curseforge.com/members/Ruukasu

### CODE REVIEW

**Comment by copygirl** [comment]
Thanks for your contribution! :heart: As with the other localization PR, I'll wait to merge this until I'm fairly certain there won't be any additional keys to be translated or changes to existing ones.

**Comment by Zerotiger** [comment]
Alright, I check kind of regularly if there has been any changes to en_us.lang on mods I've translated

**Comment by copygirl** [comment]
I updated your PR. There is two new localization keys for you to translate.

**Comment by Zerotiger** [comment]
I am not 100% sure how pushing to PR's work, but I think I did it correctly now. At least I see it listed in the "commits" tab.

**Comment by Zerotiger** [comment]
#57 Just tagging the "main issue" to make sure, it gets noticed :)

**Comment by copygirl** [comment]
Oh, I noticed by the way that you didn't update the existing keys. They `category.entity` and `entity.entries` keys. They're not directly "spawn" related anymore.

Also, another thing. While I would like to respect your wish to credit your CurseForge account, ... well let's just say it's more straightforward and useful for me to keep all the contributors' GitHub accounts. Alternatively, if it's really important to you, I can link both.

**Comment by Zerotiger** [comment]
Alright, I'll translate them, when I get home.
Don't worry about the credit, it's not that important.

**Comment by copygirl** [comment]
Awesome, thank you! 🎉

**Pull request merged**
