### PR TITLE
Added Italian Language

### PR DESCRIPTION
**Pull request by Insane-96**

### CODE REVIEW

**Comment by copygirl** [comment]
Thanks for the contribution! ❤️ Do you mind if I hold out on merging this until I'm more certain there won't be any more localization changes for the next big version?

**Comment by Insane-96** [comment]
No worries, I'll wait and translate new things as they come out

**Comment by copygirl** [comment]
I updated your pull request. Can you translate the two new keys to finish this? Thank you!

**Comment by Insane-96** [comment]
Should I remove the '#' before a string?

**Comment by copygirl** [comment]
Sorry for the wait. I wanted to ask an Italian friend to quickly look over the changes, but it's taking a bit too long to get in contact with him. I'll just merge for now. Changes can always be done, later!

**Pull request merged**
