### PR TITLE
Update pt_BR.lang

### PR DESCRIPTION
**Pull request by eduardogomesv**
Better translation for Brazilian Portuguese. Avoiding to robotic translation to better experience in game.

### CODE REVIEW

**Comment by copygirl** [comment]
Thanks for your contribution ❤️

I have a few things to mention:
- It appears you're using "SHIFT" in place where the English localization uses "sneaking". I avoided using "SHIFT" because this action can be rebound to a different key.
- The English language file skips out on using periods in some cases, and the previous translation has mirrored that. Do you think these should include periods? Also, only some of your config translations have a period, most don't.
- Also in the English version, I didn't refer to backpacks as "Backpack", but either "backpack" in case of the general options and "regular backpack" in case of the Backpack specific ones. This is in preparation of me adding more, different backpacks.
- You forgot removing the `#` in front of the non-translated lines.

**Comment by eduardogomesv** [comment]
My bad. Thank you and I'll be more careful from now.

"(Quebre a mochila para retornar como ítem e equipe novamente para aplicar)"
"(Break the backpack to turn item again and equip to apply)" on line 38
I added this line because I had difficulty understanding (I set fire to the backpack), and found a comment on CurseForge, thought it would be interesting to explain here.

**Comment by copygirl** [comment]
Looks good! Just one more thing regarding your addition, which I think is a good one, and I'm going to use it for the English language file as well: First, I don't know if you can use `\n` there. Either way I'd avoid it. I will change the line in English to:

> Controls the storage size of regular backpacks. Does not affect currently placed or equipped backpacks, turn them back into an item to apply changes

So if you could make yours the translation of that, that'd be nice!

**Comment by eduardogomesv** [comment]
Fixed. I think the way I'd use seems more natural for us.

**Comment by copygirl** [comment]
Nice, thank you again!

**Pull request merged**
