### PR TITLE
Updated Russian translation.

### PR DESCRIPTION
**Pull request by raspopov**
Slightly more correct translation.
And renamed .yml to .lang.

### CODE REVIEW

**Comment by copygirl** [comment]
Oh, whoops. Will check this later. Thanks!

**Comment by copygirl** [comment]
Pinging @dangranos to take a quick look at this ❤️

**Comment by dangranos** [comment]
While "присесть и правый клик" sounds bit... wierd, I can't think of anything else. Except for using a shortening "ПКМ", which would result in confusion. Keep it like this, unless you can think of better variant.
Next "section" for the `config.wearablebackpacks.general.` seems fine, but the "Разрешить" and "Разрешает" is a bit incosistent, compared to the older variant.
Basically, except for tiny but very minor problems which aren't even visible unless you actually look for them, it's good to go.

**Comment by raspopov** [comment]
IMHO It's a matter of time. :-) "Разрешить" - "enable", but "Разрешает" - "enables" or more precisely "Разрешено" - "enabled". But I prefer "direct orders" for users in the GUI, so second one.

**Comment by dangranos** [comment]
Well, you can either keep it or change it, I only suggested. Poke the
developer when you think it's done. I approve of the current state of
translation.

**Comment by copygirl** [comment]
Sorry for taking so long. Thanks for your input! 💚

**Pull request merged**
