### PR TITLE
es_MX translation

### PR DESCRIPTION
**Pull request by Dorzar**

### CODE REVIEW

**Comment by copygirl** [comment]
There we go, thank you ❤️

I will check the translation and fix some issues later. The file needs to be called `es_MX.lang` and I want to remove the comments on top (you'll be credited in the readme file). I hope you're okay with the latter change..?

**Comment by Dorzar** [comment]
Your welcome ^^
Do not worry about removing those lines, I'm happy to have helped the Castilian community, excellent mod you have created.

**Comment by copygirl** [comment]
Hmm.. one minor and one more major issue with the translation:

- Sneaking can be rebound to not be on the `SHIFT` key which is what you're referencing. Maybe you can change the wording on it a little?
- The config translations are too long in the default window size:
image

**Comment by Dorzar** [comment]
Point 1: Yep, i put that translation in a very specific way, fixed it.
`tooltip.wearablebackpacks.moreInfo=Presiona %1$s para más información.
tooltip.wearablebackpacks.openHint=Presiona %1$s para abrir la mochila teniéndola equipada.
tooltip.wearablebackpacks.equipHint=Equipar mochila: agácharse + rómperla.
tooltip.wearablebackpacks.equipHint.extended=Equipar mochila: agácharse + rómperla.\nDesequipar mochila: agácharse + clic\nderecho en el suelo con la mano vacia.
tooltip.wearablebackpacks.unequipHint=Desequipar mochila: agácharse + clic\nderecho en el suelo con la mano vacia.`

Sneaking = Agácharse

Point 2: My mistake
`config.wearablebackpacks.general.equipAsChestArmor=Equipar como pechera
config.wearablebackpacks.general.equipAsChestArmor.tooltip=Controla si las mochilas equipadas ocupan la ranura de la pechera.
config.wearablebackpacks.general.enableEquippedInteraction=Acceso a otras mochilas
config.wearablebackpacks.general.enableEquippedInteraction.tooltip=Controla si los jugadores pueden acceder a la mochilas de otros jugadores (y entidades) si estos la tienen equipada.
config.wearablebackpacks.general.enableSelfInteraction=Interacción propia
config.wearablebackpacks.general.enableSelfInteraction.tooltip=Controla si los jugadores pueden acceder a su mochila usando una tecla específica.
config.wearablebackpacks.general.dropAsBlockOnDeath=Soltar al morir
config.wearablebackpacks.general.dropAsBlockOnDeath.tooltip=Controla si las mochilas se colocan en el lugar de la muerte, en vez de dispersar su contenido.`

Do I have to make another Pull request?

**Comment by copygirl** [comment]
> Do I have to make another Pull request?

No you don't. [Either go to your branch and edit the file again](https://github.com/Dorzar/WearableBackpacks/blob/patch-1/src/main/resources/assets/wearablebackpacks/lang/es_MX.lang), or just go to [Files changed](https://github.com/copygirl/WearableBackpacks/pull/46/files) on this PR and click edit (the pencil) it there.

Regarding the `+`, wouldn't a simple "and" be better?

**Comment by Dorzar** [comment]
https://github.com/Dorzar/WearableBackpacks/blob/patch-1/src/main/resources/assets/wearablebackpacks/lang/es_MX.lang

Here it is finished, i test it and everything is perfect, also i add the suggestions you gave me.

P.S: Enjoy the full translation :)

**Comment by copygirl** [comment]
Thank you so much!

**Pull request merged**
